---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  tasks:
    - name: Include OS-specific variables.
      include_vars: "vars/{{ ansible_os_family }}.yml"

    # @TODO(mattjmcnaughton) Make it possible to configure whether to use the
    # `large.yml` or `small.yml` variables, depending on the type of machine
    # we are using for the install.
    - name: 
      include_vars: "vars/small.yml"

    - name: Configure the base settings of the machine.
      include: "tasks/base.yml"

    - name: Install and uninstall OS-specific packages.
      include: "tasks/packages-{{ ansible_os_family }}.yml"
      static: no
      become: yes

    - name: Configure users.
      include: "tasks/users.yml"

    - name: Configure git.
      include: "tasks/git.yml"

    - name: Perform Github account configuration.
      include: "tasks/github.yml"
      when: github_access_token is defined

    - name: Install and configure i3.
      include: "tasks/i3.yml"
      when: ansible_os_family == "Debian"

    - name: Configure dotfiles.
      include: "tasks/dotfiles.yml"

    - name: Install python and relevant packages.
      include: "tasks/python.yml"

    - name: Install Rust and relevant packages.
      include: "tasks/rust.yml"

    - name: Install Go and relevant packages.
      include: "tasks/go.yml"

    - name: Install Ruby using rbenv.
      include_role:
        name: zzet.rbenv
      become: yes

    - name: Install Docker (separately if on Linux machine).
      include_role:
        name: geerlingguy.docker
      when: ansible_os_family == "Debian"
      become: yes

    - name: Add additional system security.
      include: "tasks/security.yml"

    - name: Log manual configuration still needed.
      include: "tasks/manual-{{ ansible_os_family }}.yml"
      static: no
