---
- name: Install git autocomplete.
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    dest: "{{ git_completion_bash }}"

- name: Copy the bashrc.local configuration into place.
  template:
    src: templates/bash/bashrc.local.j2
    dest: ~/.bashrc.local

- name: Copy the `profile.local` file into place.
  template:
    src: templates/bash/profile.local.j2
    dest: ~/.profile.local

- name: Ensure the `~/.bashrc` file exists.
  file:
    path: ~/.bashrc
    state: file

- name: Ensure `~/.bashrc` loads `~/.bashrc.local`
  lineinfile:
    path: ~/.bashrc
    line: "[ -s ~/.bashrc.local ] && source ~/.bashrc.local"

- name: Ensure the `~/.profile` file exists.
  file:
    path: ~/.profile
    state: file

- name: Ensure `~/.profile` loads ~/.profile.local`.
  lineinfile:
    path: ~/.profile
    line: "[ -s ~/.profile.local ] && source ~/.profile.local"

- name: Create the utility dirs
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ utility_script_dir }}"
    - "{{ utility_bin_dir }}"

- name: Copy the directory of utility scripts.
  copy:
    src: "{{ item }}"
    dest: "{{ utility_script_dir }}/"
  with_fileglob:
    - files/bash/utility_script/*

- name: Copy in the external utility scripts.
  get_url:
    url: "{{ item.url }}"
    dest: "{{ utility_script_dir }}/{{ item.file_name }}"
  with_items:
    - { url: "https://raw.githubusercontent.com/mattjmcnaughton/brockman/master/brockman.sh", file_name: "brockman.sh" }

- name: Copy the directory of utility binaries.
  copy:
    src: "{{ item }}"
    dest: "{{ utility_bin_dir }}/"
  with_fileglob:
    - files/bash/utility_bin/*

- name: Set the utility directories to be executable only by the user.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    recurse: yes
  with_items:
    - "{{ utility_script_dir }}"
    - "{{ utility_bin_dir }}"

- name: Copy the bash.aliases configuration into place.
  copy:
    src: files/bash/bash_aliases
    dest: ~/.bash_aliases

- name: Copy tmux configuration into place.
  copy:
    src: files/tmux/tmux.conf
    dest: ~/.tmux.conf

- name: Create the `.vim/bundle` directory.
  file:
    path: ~/.vim/bundle
    state: directory

- name: Install Vundle.
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: ~/.vim/bundle/Vundle.vim

- name: Copy the vim configuration files into place.
  copy:
    src: "files/vim/{{ item }}"
    dest: "~/.{{ item }}"
  with_items:
    - "vimrc"
    - "vimrc.local"
    - "vimrc.bundles"

- name: Install Plugins using Vundle.
  command: vim +PluginInstall +qall
