---
- name: Ensure SELinux is enabled in targeted mode.
  selinux:
    policy: targeted
    state: enforcing
  become: yes
  when: ansible_os_family == "Debian"

# By default, will allow loopback and established/recognized incoming
# connections
- name: Install Firewall allowing no external connections.
  include_role:
    name: geerlingguy.firewall
  vars:
    firewall_allowed_tcp_ports: []
  become: yes
  when: ansible_os_family == "Debian"

- name: Ensure sshd_config file exists
  file:
    path: /etc/ssh/sshd_config
    state: touch
    mode: "u+rw,g+r,o+r"
  become: yes

- name: Disable root ssh and password ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }
    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
  become: yes
